### ISSUE TITLE
Autoload failed with error TypeError: cannot serialize None (type NoneType)

### ISSUE THREAD

**Issue by Costya-Y** [QualiSystems/cloudshell-L1-mrv#8]
Traceback (most recent call last):
  File "C:\Program Files (x86)\f\CloudShell\Server\Drivers\cloudshell-L1-mrv\lib\site-packages\cloudshell\layer_one\core\connection_handler.py", line 46, in run
    CommandResponsesBuilder.to_string(CommandResponsesBuilder.build_xml_result(responses)))
  File "C:\Program Files (x86)\f\CloudShell\Server\Drivers\cloudshell-L1-mrv\lib\site-packages\cloudshell\layer_one\core\response\command_responses_builder.py", line 73, in to_string
    return ElementTree.tostring(root, encoding='UTF-8', method='xml').replace('\n', '\r\n')
  File "C:\Program Files (x86)\f\CloudShell\Server\python\2.7.10\Lib\xml\etree\ElementTree.py", line 1126, in tostring
    ElementTree(element).write(file, encoding, method=method)
  File "C:\Program Files (x86)\f\CloudShell\Server\python\2.7.10\Lib\xml\etree\ElementTree.py", line 820, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "C:\Program Files (x86)\f\CloudShell\Server\python\2.7.10\Lib\xml\etree\ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "C:\Program Files (x86)\f\CloudShell\Server\python\2.7.10\Lib\xml\etree\ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "C:\Program Files (x86)\f\CloudShell\Server\python\2.7.10\Lib\xml\etree\ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "C:\Program Files (x86)\f\CloudShell\Server\python\2.7.10\Lib\xml\etree\ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "C:\Program Files (x86)\f\CloudShell\Server\python\2.7.10\Lib\xml\etree\ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "C:\Program Files (x86)\f\CloudShell\Server\python\2.7.10\Lib\xml\etree\ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "C:\Program Files (x86)\f\CloudShell\Server\python\2.7.10\Lib\xml\etree\ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "C:\Program Files (x86)\f\CloudShell\Server\python\2.7.10\Lib\xml\etree\ElementTree.py", line 932, in _serialize_xml
    v = _escape_attrib(v, encoding)
  File "C:\Program Files (x86)\f\CloudShell\Server\python\2.7.10\Lib\xml\etree\ElementTree.py", line 1092, in _escape_attrib
    _raise_serialization_error(text)
  File "C:\Program Files (x86)\f\CloudShell\Server\python\2.7.10\Lib\xml\etree\ElementTree.py", line 1052, in _raise_serialization_error
    "cannot serialize %r (type %s)" % (text, type(text).__name__)
TypeError: cannot serialize None (type NoneType)

**Comment by yaroslavNqualisystems** [comment]
The Issue related to cloudshell-l1-networking-core package.
Open: https://github.com/QualiSystems/cloudshell-L1-networking-core/issues/30
